export const StrategistCaapSassConst = {
    "American Funds - Standard & Tax-aware": 0,
    "Fidelity Institutional Asset Management - Index Focused": 0,
    "Franklin Templeton - Core": 0.2,
    "Nuveen - Core ESG": 0,
    "PIMCO - Fixed Income": 0.05,
    "Vanguard - Core": 0,
    "State Street - ETF": 0,
    "BlackRock - Long Horizon ETF": 0
  }

 export  const StrategistCaapConst ={
    "3Edge Asset Management": 0.35,
    "American Funds - Standard & Tax-aware": 0,
    "American Funds - Retirement Income": 0,
    "BlackRock - Long Horizon ETF": 0,
    "BlackRock - Target Allocation": 0,
    "Brinker Capital": 0,
    "Fidelity Institutional Asset Management - Fixed Income": 0,
    "Fidelity Institutional Asset Management - Index Focused": 0,
    "First Trust": 0,
    "Franklin Templeton - Alternative Completion": 0.05,
    "Franklin Templeton - Diversified ESG": 0,
    "Goldman Sachs": 0.15,
    "Horizon Investments - Hybrid": 0.3,
    "Horizon Investments - Risk Assist": 0,
    "Horizon Investments - Real Spend": 0,
    "iM Global Partner - Standard, Tax-sensitive & ETF": 0.1,
    "iM Global Partner - ESG": 0,
    "JP Morgan": 0,
    "Morningstar - Absolute Return & Retirement Income": 0,
    "Morningstar - Active/Passive": 0.1,
    "Morningstar - ETF": 0.17,
    "Nuveen - ESG & Tax-exempt": 0,
    "Ocean Park": 0.05,
    "OneAscent Investment Solutions": 0.25,
    "PIMCO - Fixed Income": 0.05,
    "PIMCO - Tax-aware Fixed Income": 0.05,
    "PMC": 0.1,
    "Principal Global Investors - Public Growth / Public Income": 0.2,
    "Richard Bernstein Advisors": 0.35,
    "Russell Investments - Risk Assist": 0.2,
    "Russell Investments - Hybrid": 0,
    "SEI": 0.15,
    "State Street - ETF": 0,
    "State Street - Risk Assist": 0.2,
    "Symmetry Partners - Panoramic": 0,
    "Symmetry Partners - Risk Assist": 0.2,
    "Symmetry Partners - Structured Bond": 0.23,
    "T. Rowe Price - Low Duration": 0,
    "Vanguard": 0,
    "Voya Investment Management": 0.25
  }